### ISSUE TITLE
Is 5.01 and 5.1 compatible?

### ISSUE THREAD

**Issue by youngjae-avikus** [hlld/deepstream-yolov5#3]
Hello, only 5.0 is specified in README, so I'm curious if it's possible to release 5.x later. Thank you

**Comment by hlld** [comment]
It should be compatible with nvds 5.x.

**Comment by youngjae-avikus** [comment]
I can see that the input width, height that the tensorrt engine accepts in yololayer.h is defined.
I know that the letterbox is applied during the yolo training and is not 1:1 of the actual image ratio, and I wonder how it is processed in this code. Is it simply resize to 1:1?

**Comment by hlld** [comment]
letterbox is applied in this repo, u can check it.
